import = [
    "/Users/tdinelli/.config/alacritty/alabaster.toml"
]

[bell]
animation = "EaseOutExpo"
color = "0xffffff"
duration = 0

[colors.cursor]
cursor = "#fb1d1d"
text = "#ffffff"

[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"
live_config_reload = "true"

[font]
size = 18.0

[font.normal]
# family = "Hack Nerd Font"
family = "JetBrainsMono Nerd Font"
# family = "juliamono"

[scrolling]
history = 5000
multiplier = 3

[shell]
program = "/bin/zsh"

[window]
decorations = "full"
startup_mode = "Windowed"
option_as_alt = "OnlyLeft"

[window.padding]
x = 6
y = 6
